# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

    args: ['--fix=no']

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
    -   id: black
        args: ["--line-length=100"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        additional_dependencies:
        -   pydantic==2.12.5
        -   sqlmodel==0.0.37

-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-pyproject==1.2.4
